# Generated by Django 5.1.2 on 2024-11-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bvn',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
