# Generated by Django 5.1.2 on 2025-04-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_fakeloginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='monnifytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('first_deposit', 'First Deposit'), ('regular', 'Regular Deposit')], default='regular', max_length=20),
        ),
    ]
