# Generated by Django 5.1.2 on 2025-04-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_monnifytransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
