# Generated by Django 5.1.2 on 2024-11-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_remove_customuser_dob_remove_customuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nin',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
