# Generated by Django 5.1.2 on 2025-04-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_customuser_failed_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_filled_fund_form',
            field=models.BooleanField(default=False),
        ),
    ]
