# Generated by Django 4.2.13 on 2025-09-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_paystacktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buydata',
            name='data_type',
            field=models.CharField(blank=True, choices=[('SME', 'SME'), ('GIFTING', 'GIFTING'), ('CORPORATE GIFTING', 'Corporate Gifting'), ('SME2', 'SME2'), ('DATA COUPONS', 'Data Coupons'), ('Glo Data', 'Glo Data'), ('Glo SME Data', 'Glo SME Data'), ('9mobile Data', '9mobile Data'), ('9mobile SME Data', '9mobile SME Data')], max_length=20, null=True),
        ),
    ]
