# Generated by Django 5.1.2 on 2024-12-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyairtime',
            name='response_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
