# Generated by Django 5.1.2 on 2024-12-02 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_buyairtime_response_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyairtime',
            name='response_data',
        ),
    ]
