# Generated by Django 5.1.2 on 2024-12-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_remove_buyairtime_response_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyairtime',
            name='airtime_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
