# Generated by Django 5.1.2 on 2024-12-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0013_buyairtime_date_created_buyairtime_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyairtime',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
