# Generated by Django 5.1.2 on 2024-12-17 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_alter_buyairtime_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='data_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('airtime_purchase', 'Airtime Purchase'), ('data_purchase', 'Data Purchase')], max_length=20),
        ),
        migrations.CreateModel(
            name='BuyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.IntegerField(choices=[(1, 'MTN'), (2, 'GLO'), (3, '9MOBILE'), (4, 'AIRTEL')])),
                ('data_type', models.CharField(blank=True, choices=[('Glo Data', 'Glo Data'), ('Glo SME Data', 'Glo SME Data'), ('9mobile Data', '9mobile Data'), ('9mobile SME Data', '9mobile SME Data')], max_length=20, null=True)),
                ('mobile_number', models.CharField(max_length=11)),
                ('data_plan', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bypass_validator', models.BooleanField(default=False)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='failed', max_length=20)),
                ('data_response', models.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
