# Generated by Django 5.1.2 on 2024-12-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_transaction_data_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buydata',
            name='bypass_validator',
        ),
    ]
