# Generated by Django 5.1.4 on 2025-01-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0017_tvservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvservice',
            name='showmax_type',
            field=models.CharField(blank=True, choices=[('full', 'Full - N2,900'), ('mobile_only', 'Mobile Only - N1,450'), ('sports_full', 'Sports Full - N6,300'), ('sports_mobile_only', 'Sports Mobile Only - N3,200')], max_length=20, null=True),
        ),
    ]
