# Generated by Django 5.1.2 on 2025-02-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0019_tvservice_user_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvservice',
            name='data_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
