# Generated by Django 5.1.2 on 2025-02-04 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0021_buyairtime_transaction_id_buydata_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
