# Generated by Django 5.1.2 on 2025-02-14 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0023_electricitybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitybill',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ElectricityBill', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
