# Generated by Django 5.1.2 on 2025-02-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0024_electricitybill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitybill',
            name='data_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('airtime_purchase', 'Airtime Purchase'), ('data_purchase', 'Data Purchase'), ('TV_Subscription', 'TV SUBSCRIPTION'), ('ElectricityBill', 'Electricity Bill')], max_length=20),
        ),
    ]
