# Generated by Django 5.1.2 on 2025-02-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0025_electricitybill_data_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitybill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='electricitybill',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='electricitybill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
