# Generated by Django 5.1.2 on 2025-02-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0026_electricitybill_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitybill',
            name='transaction_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
