# Generated by Django 5.1.2 on 2025-02-17 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0027_alter_electricitybill_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitybill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Electricity_Bill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('airtime_purchase', 'Airtime Purchase'), ('data_purchase', 'Data Purchase'), ('TV_Subscription', 'TV SUBSCRIPTION'), ('Electricity_Bill', 'Electricity Bill')], max_length=20),
        ),
    ]
