# Generated by Django 5.1.2 on 2025-03-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0029_customuser_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaecPinGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExamType', models.CharField(choices=[('WASSCE/GCE', 'WASSCE/GCE')], max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('quantity', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_response', models.JSONField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
