# Generated by Django 5.1.2 on 2025-03-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0030_waecpingenerator'),
    ]

    operations = [
        migrations.CreateModel(
            name='JambRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('DE', 'Direct Entry (DE)')], default='DE', max_length=2)),
                ('jamb_profile_id', models.CharField(max_length=50, verbose_name='JAMB Profile ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='Phone Number')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_response', models.JSONField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'JAMB Registration',
                'verbose_name_plural': 'JAMB Registrations',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('airtime_purchase', 'Airtime Purchase'), ('data_purchase', 'Data Purchase'), ('TV_Subscription', 'TV SUBSCRIPTION'), ('Electricity_Bill', 'Electricity Bill'), ('electricity_payment', 'Electricity Payment'), ('jamb_registration', 'JAMB Registration')], max_length=20),
        ),
    ]
