# Generated by Django 5.1.2 on 2025-03-29 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0031_jambregistration_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jambregistration',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jamb_registration', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waecpingenerator',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='electricity_payment', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
