# Generated by Django 5.1.2 on 2025-03-29 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0032_jambregistration_user_waecpingenerator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jambregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jamb_registration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('airtime_purchase', 'Airtime Purchase'), ('data_purchase', 'Data Purchase'), ('TV_Subscription', 'TV SUBSCRIPTION'), ('Electricity_Bill', 'Electricity Bill'), ('waec_pin_generator', 'WAEC PIN'), ('jamb_registration', 'JAMB Registration')], max_length=20),
        ),
        migrations.AlterField(
            model_name='waecpingenerator',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waec_pin_generator', to=settings.AUTH_USER_MODEL),
        ),
    ]
