# Generated by Django 5.1.2 on 2025-03-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0033_alter_jambregistration_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waecpingenerator',
            name='serviceID',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waecpingenerator',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
