# Generated by Django 5.1.2 on 2025-04-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0034_waecpingenerator_serviceid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jambregistration',
            name='serviceID',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
