# Generated by Django 5.1.2 on 2025-04-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0035_jambregistration_serviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jambregistration',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='Phone Number'),
        ),
    ]
