# Generated by Django 5.1.2 on 2025-04-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0039_customuser_referral_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_deposit_reward_given',
            field=models.BooleanField(default=False),
        ),
    ]
