# Generated by Django 5.1.2 on 2025-04-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0041_siteconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteConfig',
        ),
    ]
