# Generated by Django 5.1.2 on 2025-04-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0042_delete_siteconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('Airtime Purchase', 'Airtime Purchase'), ('Data Purchase', 'Data Purchase'), ('TV_Subscription', 'TV SUBSCRIPTION'), ('Electricity_Bill', 'Electricity Bill'), ('waec_pin_generator', 'WAEC PIN'), ('jamb_registration', 'JAMB Registration')], max_length=20),
        ),
    ]
